//전체 도서
export const GET_ALL_BOOKS_REQUEST = 'GET_ALL_BOOKS_REQUEST';
export const GET_ALL_BOOKS_SUCCESS = 'GET_ALL_BOOKS_SUCCESS';
export const GET_ALL_BOOKS_FAILURE = 'GET_ALL_BOOKS_FAILURE';

//도서 디테일
export const GET_BOOK_REQUEST = 'GET_BOOK_REQUEST';
export const GET_BOOK_SUCCESS = 'GET_BOOK_SUCCESS';
export const GET_BOOK_FAILURE = 'GET_BOOK_FAILURE';

//그룹별 전체 도서
export const GET_BOOKS_GROUPNAME_REQUEST = 'GET_BOOKS_GROUPNAME_REQUEST';
export const GET_BOOKS_GROUPNAME_SUCCESS = 'GET_BOOKS_GROUPNAME_SUCCESS';
export const GET_BOOKS_GROUPNAME_FAILURE = 'GET_BOOKS_GROUPNAME_FAILURE';

//Book배열 비워줌
export const RESET_BOOKS = 'RESET_BOOKS';
