//전체 도서
export const GET_ALL_BOOKS_REQUEST = 'GET_ALL_BOOKS_REQUEST';
export const GET_ALL_BOOKS_SUCCESS = 'GET_ALL_BOOKS_SUCCESS';
export const GET_ALL_BOOKS_FAILURE = 'GET_ALL_BOOKS_FAILURE';

//도서 디테일
export const GET_BOOK_REQUEST = 'GET_BOOK_REQUEST';
export const GET_BOOK_SUCCESS = 'GET_BOOK_SUCCESS';
export const GET_BOOK_FAILURE = 'GET_BOOK_FAILURE';

//도서 그룹별
export const GET_BOOKS_BY_GROUP_REQUEST = 'GET_BOOKS_BY_GROUP_REQUEST';
export const GET_BOOKS_BY_GROUP_SUCCESS = 'GET_BOOKS_BY_GROUP_SUCCESS';
export const GET_BOOKS_BY_GROUP_FAILURE = 'GET_BOOKS_BY_GROUP_FAILURE';

//도서 검색
export const GET_BOOKS_SEARCH_REQUEST = 'GET_BOOKS_SEARCH_REQUEST';
export const GET_BOOKS_SEARCH_SUCCESS = 'GET_BOOKS_SEARCH_SUCCESS';
export const GET_BOOKS_SEARCH_FAILURE = 'GET_BOOKS_SEARCH_FAILURE';

//도서 isbn 검색
export const GET_BOOK_ISBN_SEARCH_REQUEST = 'GET_BOOK_ISBN_SEARCH_REQUEST';
export const GET_BOOK_ISBN_SEARCH_SUCCESS = 'GET_BOOK_ISBN_SEARCH_SUCCESS';
export const GET_BOOK_ISBN_SEARCH_FAILURE = 'GET_BOOK_ISBN_SEARCH_FAILURE';

// 리셋 그룹별 도서
export const RESET_GROUP_BOOKS = 'RESET_GROUP_BOOKS';
