//add item to cart
export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const ADD_TO_CART_FAILURE = 'ADD_TO_CART_FAILURE';

export const GET_ITEMS_IN_CART_REQUEST = 'GET_ITEMS_IN_CART_REQUEST';
export const GET_ITEMS_IN_CART_SUCCESS = 'GET_ITEMS_IN_CART_SUCCESS';
export const GET_ITEMS_IN_CART_FAILURE = 'GET_ITEMS_IN_CART_FAILURE';

export const UPDATE_CART_ITEM_REQUEST = 'UPDATE_CART_ITEM_REQUEST';
export const UPDATE_CART_ITEM_SUCCESS = 'UPDATE_CART_ITEM_SUCCESS';
export const UPDATE_CART_ITEM_FAILURE = 'UPDATE_CART_ITEM_FAILURE';

export const DELETE_CART_ITEM_REQUEST = 'DELETE_CART_ITEM_REQUEST';
export const DELETE_CART_ITEM_SUCCESS = 'DELETE_CART_ITEM_SUCCESS';
export const DELETE_CART_ITEM_FAILURE = 'DELETE_CART_ITEM_FAILURE';

export const SET_QUANTITY_IN_LOCALSTORAGE = 'SET_QUANTITY_IN_LOCALSTORAGE';

export const CLEAR_CART = 'CLEAR_CART'; //전체삭제
