//카테고리
export const GET_CATEGORY_REQUEST = 'GET_CATEGORY_REQUEST';
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';
export const GET_CATEGORY_FAILURE = 'GET_CATEGORY_FAILURE';

export const GET_CATEGORIES_BY_ID_REQUEST = 'GET_CATEGORIES_BY_ID_REQUEST';
export const GET_CATEGORIES_BY_ID_SUCCESS = 'GET_CATEGORIES_BY_ID_SUCCESS';
export const GET_CATEGORIES_BY_ID_FAILURE = 'GET_CATEGORIES_BY_ID_FAILURE';

export const GET_CATEGORY_BY_ID_REQUEST = 'GET_CATEGORY_BY_ID_REQUEST';
export const GET_CATEGORY_BY_ID_SUCCESS = 'GET_CATEGORY_BY_ID_SUCCESS';
export const GET_CATEGORY_BY_ID_FAILURE = 'GET_CATEGORY_BY_ID_FAILURE';

export const RESET_CATEGORY_BY_ID_REQUEST = 'RESET_CATEGORY_BY_ID_REQUEST';

export const SET_SELECTED_CATEGORY_IDS = 'SET_SELECTED_CATEGORY_IDS';
export const SET_EXPANDED_CATEGORY_IDS = 'SET_EXPANDED_CATEGORY_IDS';
export const SET_SUB_CATEGORY_IDS = 'SET_SUB_CATEGORY_IDS';
