export const MAKE_AN_ORDER_REQUEST = 'MAKE_AN_ORDER_REQUEST';
export const MAKE_AN_ORDER_SUCCESS = 'MAKE_AN_ORDER_SUCCESS';
export const MAKE_AN_ORDER_FAILURE = 'MAKE_AN_ORDER_FAILURE';
export const GET_ORDER_HISTORY_REQUEST = 'GET_ORDER_HISTORY_REQUEST';
export const GET_ORDER_HISTORY_SUCCESS = 'GET_ORDER_HISTORY_SUCCESS';
export const GET_ORDER_HISTORY_FAILURE = 'GET_ORDER_HISTORY_FAILURE';
