//add review
export const ADD_REVIEW_REQUEST = 'ADD_REVIEW_REQUEST';
export const ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS';
export const ADD_REVIEW_FAILURE = 'ADD_REVIEW_FAILURE';

export const GET_ALL_REVIEWS_OF_BOOK_REQUEST = 'GET_ALL_REVIEWS_OF_BOOK_REQUEST';
export const GET_ALL_REVIEWS_OF_BOOK_SUCCESS = 'GET_ALL_REVIEWS_OF_BOOK_SUCCESS';
export const GET_ALL_REVIEWS_OF_BOOK_FAILURE = 'GET_ALL_REVIEWS_OF_BOOK_FAILURE';

export const EDIT_REVIEW_REQUEST = 'EDIT_REVIEW_REQUEST';
export const EDIT_REVIEW_SUCCESS = 'EDIT_REVIEW_SUCCESS';
export const EDIT_REVIEW_FAILURE = 'EDIT_REVIEW_FAILURE';

export const DELETE_REVIEW_REQUEST = 'DELETE_REVIEW_REQUEST';
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS';
export const DELETE_REVIEW_FAILURE = 'DELETE_REVIEW_FAILURE';
