//Wish List
export const GET_WISHLIST_REQUEST = 'GET_WISHLIST_REQUEST';
export const GET_WISHLIST_SUCCESS = 'GET_WISHLIST_SUCCESS';
export const GET_WISHLIST_FAILURE = 'GET_WISHLIST_FAILURE';

export const TOGGLE_WISHLIST_REQUEST = 'TOGGLE_WISHLIST_REQUEST';
export const TOGGLE_WISHLIST_SUCCESS = 'TOGGLE_WISHLIST_SUCCESS';
export const TOGGLE_WISHLIST_FAILURE = 'TOGGLE_WISHLIST_FAILURE';
